sude: required

services:
  - docker

before_install:
  - docker build -t jajacontainer/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true jajacontainer/react-test npm test

after_succes:
  - docker build -t jajacontainer/multi-client ./client
  - docker build -t jajacontainer/multi-server ./server
  - docker build -t jajacontainer/multi-nginx ./nginx
  - docker build -t jajacontainer/multi-worker ./worker
  ## Login Docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ## Take all the image to our own docker hub
  - docker push jajacontainer/multi-client
  - docker push jajacontainer/multi-server
  - docker push jajacontainer/multi-nginx
  - docker push jajacontainer/multi-worker
